// Content source for the newer guide pages generated by build-guide-pages.js.
// Kept as data (not HTML) so the pages stay consistent with the live docs
// layout. Body fields may contain inline HTML (<code>, <em>, <strong>, <a>);
// the generator strips tags for JSON-LD and escapes attributes.

module.exports = [
  {
    slug: "stacked-prs",
    title: "Stacked PRs",
    breadcrumb: "Stacked workflow",
    description:
      "Work in stacks the way Git Navigator now models them: each layer is a branch that can hold multiple commits. Push a whole stack, diff against the branch below, and pull onto the branch you are stacked on.",
    keywords: ["stacked prs", "stacked branches git", "stacked diffs", "git stack workflow", "stack mode git navigator"],
    ogImage: "static/stacked-prs.png",
    hero: {
      heading: "Stacks built from real branches",
      lead:
        "Git Navigator models a stack the way your team reviews it: <strong>each layer is a branch</strong> that can hold several commits — not one branch per commit. Push a whole stack respecting each branch's remote, diff a commit against the branch below it, and pull the current branch onto the branch it is stacked on.",
    },
    heroMedia: {
      type: "image",
      src: "static/stacked-prs.png",
      alt: "Git Navigator in stack mode showing a two-layer stack: feature/ui stacked on feature/api on main",
      caption:
        "A two-layer stack rendered in stack mode: feature/ui sits on feature/api, which sits on main — each layer a branch with its own commits.",
    },
    highlightsTitle: "How stacking works now",
    highlights: [
      { title: "A layer is a branch, not a commit", body: "A stack layer is a branch that can hold <em>several</em> commits. Pushing a branch — or a whole stack — no longer means one branch per commit, so your stack maps cleanly onto the PRs your team actually reviews." },
      { title: "Each branch keeps its own remote", body: "A stack push respects every layer's configured upstream, so branches that track different remotes still push where they should in a single flow." },
      { title: "Diff against the branch below", body: "Diff a commit against any branch it is stacked on. Git Navigator widens the commit and file range one dependency layer at a time instead of jumping straight to the default branch — so you review exactly what a layer adds on top of the one beneath it." },
      { title: "Pull onto the branch you are stacked on", body: "Pull the current branch onto any strict-ancestor branch in its stack. Dependencies that have upstreams are fetched and fast-forwarded first, and stack mode carries descendant branches along with the rebase so the whole stack stays aligned." },
    ],
    steps: {
      title: "Working a stack",
      items: [
        { title: "Turn on stack mode", body: "Toggle <strong>Stack</strong> in the graph header. Stack mode keeps descendant commits aligned when you amend or rebase, and shows the full stack rather than collapsing non-tip commits." },
        { title: "Build layers as branches", body: "Branch each layer off the one below it and commit freely — a layer can carry as many commits as the change needs. The graph labels each layer with its branch." },
        { title: "Review layer by layer", body: "Diff a commit against the branch it is stacked on to see only what that layer adds, widening one dependency at a time toward the base." },
        { title: "Push or pull the stack", body: "Push a branch or the whole stack — each layer goes to its own remote — or pull the current branch onto an ancestor branch, fast-forwarding dependencies first and carrying descendants along." },
      ],
    },
    faqs: [
      { q: "How is a stack layer modeled in Git Navigator?", a: "As a branch that can contain multiple commits. Earlier stacking modeled one branch per commit; since v0.4.0 a layer is a real branch, so pushing a branch or a stack no longer forces a branch per commit and each branch's configured remote is respected." },
      { q: "Can I diff a commit against the branch below it in the stack?", a: "Yes. Git Navigator can diff a commit against any branch it is stacked on, widening the commit and file range one dependency layer at a time rather than jumping directly to the default branch — so you see exactly what each layer contributes." },
      { q: "What does pulling onto a stacked branch do?", a: "It pulls the current branch onto a strict-ancestor branch it is stacked on. Dependency branches with upstreams are fetched and fast-forwarded first, and in stack mode descendant branches are carried along with the rebase so the whole stack stays consistent." },
      { q: "What is the difference between stack mode and branch mode?", a: 'Stack mode keeps descendant commits aligned when you amend or rebase and shows the full stack; branch mode keeps operations scoped to the current branch. See the <a href="stack.html">Branch vs Stack mode</a> guide for the full comparison.' },
    ],
    prev: { href: "stack.html", label: "Branch vs Stack mode" },
    next: { href: "stack_reviewer.html", label: "Stack Reviewer" },
  },

  {
    slug: "folder-mode",
    title: "Folder Mode",
    breadcrumb: "Changes & files",
    description:
      "Open any directory in Git Navigator — even one that is not a git repository yet. Browse and search files, then initialize a repository in place when the work is worth tracking.",
    keywords: ["open folder git gui", "non-git directory", "git init gui", "initialize repository", "file browser git navigator"],
    ogImage: "static/folder-mode-step-01.png",
    hero: {
      heading: "Open any folder — git optional",
      lead:
        "Point Git Navigator at a directory that is not a git repository and it opens in <strong>folder mode</strong>. Every git-backed surface offers to <em>initialize a repository</em>, while the Files activity keeps working — so you can browse and search a scratch folder now and start tracking it the moment it matters.",
    },
    heroMedia: {
      type: "image",
      src: "static/folder-mode-step-01.png",
      alt: "Git Navigator open on a non-git directory, offering to initialize a repository",
      caption: "A plain project folder with no <code>.git</code>: the graph surface offers to initialize a repository instead of erroring.",
    },
    highlightsTitle: "What folder mode gives you",
    highlights: [
      { title: "Initialize in place, when you are ready", body: "Git-backed surfaces don't error on a non-repo — they show a clear <em>Initialize repository</em> offer. Accept it and the same folder becomes a real repo without reopening anything." },
      { title: "The Files activity stays fully usable", body: "Browse the whole tree, open files in the CodeMirror viewer, and edit them — no repository required. Folder mode is a first-class way to use Git Navigator as a plain file explorer." },
      { title: "Search without an index", body: "Filename filter and content search both work outside a repo: the search shells out to <code>git grep --no-index --exclude-standard</code>, so results honor your <code>.gitignore</code> even before <code>git init</code>." },
      { title: "Honors .gitignore and survives relaunch", body: "The tree walk uses the same ignore rules a repo would, dimming ignored entries like <code>dist/</code>. Folder mode also refreshes on external changes and is restored when you relaunch — a folder is just never silently persisted as your default repository." },
    ],
    walkthroughTitle: "Folder mode, end to end",
    walkthrough: [
      { caption: "Opening a directory with no <code>.git</code> boots Git Navigator in folder mode. The commit-graph surface replaces its history with a clear offer to <strong>initialize a repository</strong> — nothing errors, and the title bar still names the folder you opened." },
      { caption: "Switch to the Files activity and the folder is fully browsable. The tree walks the directory with the same ignore rules a repo would use, so <code>dist/</code> shows dimmed as an ignored entry while your source files stay crisp." },
      { caption: "Select a file and it opens in the CodeMirror viewer (Markdown and HTML also offer a rendered preview) — read, search, and edit all work without a repository behind them." },
    ],
    steps: {
      title: "Using a folder before it is a repo",
      items: [
        { title: "Open the directory", body: "Point Git Navigator at any folder. If it is not a git repository, the app opens it in folder mode automatically instead of refusing to open it." },
        { title: "Browse and search freely", body: "The Files activity, filename filter, and <code>git grep</code> content search all work on the raw directory, honoring <code>.gitignore</code> rules as it walks the tree." },
        { title: "Initialize when it matters", body: "When the work is worth tracking, take the <em>Initialize repository</em> offer on any git-backed surface. The folder becomes a real repo in place — no need to reopen it." },
      ],
    },
    faqs: [
      { q: "What happens if I open a folder that is not a git repository?", a: 'Git Navigator opens it in folder mode. Instead of erroring, the commit graph and other git-backed surfaces show an "Initialize repository" offer, and the Files activity works normally so you can browse and edit right away.' },
      { q: "Can I search a folder that is not under version control?", a: "Yes. Both the filename filter and content search work in folder mode. Content search runs <code>git grep --no-index --exclude-standard</code>, which searches the directory and still honors <code>.gitignore</code> even though there is no repository yet." },
      { q: "Does folder mode remember the folder when I relaunch?", a: "Folder mode is restored on relaunch so you get back what you had open, with the same initialize offer. A folder is intentionally never persisted as your default repository, so it won't be mistaken for a repo the next time you start fresh." },
      { q: "Is folder mode available in the VS Code extension too?", a: "Both runtimes support opening non-git directories. In VS Code, manual open works and the panel returns the folder-mode state; in the desktop app the folder picker falls back to folder mode whenever the chosen path is not a repository." },
    ],
    prev: { href: "file-explorer.html", label: "File Explorer" },
    next: { href: "conflict-resolution.html", label: "Conflict Resolution" },
  },

  {
    slug: "appearance",
    title: "Appearance: Color Schemes & Fonts",
    breadcrumb: "Customization & AI",
    description:
      "Make the Git Navigator desktop app yours: pick a color scheme for light and dark mode independently, and set the interface and monospace fonts from those installed on your device.",
    keywords: ["git navigator theme", "color scheme", "dark mode git client", "custom fonts", "github primer theme"],
    ogImage: "static/appearance-step-01.png",
    hero: {
      heading: "Make it look the way you think",
      lead:
        "The Git Navigator desktop app puts appearance in your hands: choose <strong>when</strong> light or dark mode applies, pick a <strong>color scheme</strong> for each mode independently, and set the interface and monospace <strong>fonts</strong> from those installed on your device.",
    },
    heroMedia: {
      type: "image",
      src: "static/appearance-step-01.png",
      alt: "Git Navigator Settings showing the Theme card with appearance and color-scheme selectors",
      caption: "The Theme card in Settings: choose when light or dark applies, then pick a color scheme for each mode.",
    },
    highlightsTitle: "What you can customize",
    highlights: [
      { title: "Light and dark, decided separately", body: "Choose <em>Follow OS</em>, <em>Light</em>, or <em>Dark</em> for when each mode applies — then pick a distinct color scheme for light and for dark, so switching modes never forces a palette you dislike." },
      { title: "Swappable color schemes", body: "Ship with a warm default <em>navigator</em> palette, a <em>GitHub Primer</em> scheme, and other popular schemes. Only the selector relevant to your current appearance is shown, and schemes are listed alphabetically." },
      { title: "Your interface and code fonts", body: "Set the application font and the monospace (code/diff) font from the fonts installed on your device, or leave either on <em>Default</em> to use the built-in faces. If no device fonts are detected, the app says so instead of offering an empty list." },
      { title: "Honest about what it bundles", body: "Settings includes third-party license disclosures, with the full license text for the bundled themes — so the appearance you pick is fully accounted for." },
    ],
    walkthroughTitle: "Personalizing the desktop app",
    walkthrough: [
      { caption: "Open Settings and the <strong>Theme</strong> card comes first. The <em>Appearance</em> selector decides when light or dark mode applies — <em>Follow OS</em>, <em>Light</em>, or <em>Dark</em>." },
      { caption: "Below it, pick a <strong>color scheme</strong> for each mode independently. Only the selector for your current appearance is shown; schemes such as the default <em>navigator</em> palette and <em>GitHub Primer</em> are listed alphabetically." },
      { caption: "The <strong>Fonts</strong> card sets the interface and monospace fonts from those installed on your device. Leave either on <em>Default</em> to use the built-in faces — the monospace choice drives the graph, diffs, and file views." },
    ],
    steps: {
      title: "Set it up in three moves",
      items: [
        { title: "Open Settings", body: "Click the gear icon at the bottom of the activity rail to open the Settings activity in the desktop app." },
        { title: "Pick appearance, then schemes", body: "Choose when light/dark applies in the Theme card, then select a color scheme for each mode. The change applies immediately." },
        { title: "Choose your fonts", body: "In the Fonts card, set the app and monospace fonts from your installed faces, or keep the built-in defaults." },
      ],
    },
    faqs: [
      { q: "Can I use a different color scheme for light and dark mode?", a: "Yes. Appearance and color scheme are separate choices: you decide when light or dark applies, then pick a distinct scheme for each mode. Git Navigator only shows the scheme selector relevant to your current appearance." },
      { q: "Which color schemes are available?", a: "A warm default \"navigator\" palette, a GitHub Primer scheme, and other popular schemes, selectable independently from light/dark mode. Schemes are sorted alphabetically in the selector, and the full license text for bundled themes is disclosed in Settings." },
      { q: "Can I change the font Git Navigator uses?", a: "Yes — both the application font and the monospace font are configurable from the fonts installed on your device. Leave either on Default to use the built-in faces. The monospace font is what the commit graph, diffs, and file views render with." },
      { q: "What if no fonts are detected on my machine?", a: "The Fonts card falls back to the built-in defaults and shows a note explaining that no device fonts were detected, rather than presenting an empty selector." },
      { q: "Is appearance customization in the VS Code extension too?", a: "The color-scheme and font controls are part of the standalone desktop app. In the VS Code extension, Git Navigator follows your editor theme so it stays consistent with the rest of VS Code." },
    ],
    prev: { href: "conflict-resolution.html", label: "Conflict Resolution" },
    next: { href: "ai-assistance.html", label: "AI Assistance" },
  },

  {
    slug: "ai-assistance",
    title: "AI Assistance",
    breadcrumb: "Customization & AI",
    description:
      "Optional, local-first AI help for commit workflows: generate commit messages from your diff and plan how to split a large change — using your editor's language model or a local CLI, with no Git Navigator backend.",
    keywords: ["ai commit message", "ai split commit", "git commit message generator", "local-first ai git", "claude code codex git"],
    hero: {
      heading: "AI for the tedious parts — on your terms",
      lead:
        "Git Navigator's AI help is optional and local-first. It drafts commit messages from your staged diff and proposes how to split an overgrown change into focused commits — using your editor's language model (VS Code) or a local CLI such as Claude Code or Codex on the desktop. There is no Git Navigator backend in the loop.",
    },
    heroMedia: {
      type: "video",
      src: "static/ai-split-and-commit.mp4",
      caption: "Asking AI to plan a split of a large change, then committing the focused pieces.",
    },
    highlightsTitle: "Where AI helps",
    highlights: [
      { title: "Generate commit messages", body: "Draft a commit message from the current staged diff, then edit it before committing. The message is a starting point you own, not an automatic commit." },
      { title: "Plan split commits", body: 'Ask AI to suggest how a large change should be divided, then use Git Navigator\'s <a href="uncommitted-changes.html">hunk-level split</a> to carry out the plan by selecting the code blocks for each commit.' },
      { title: "Local-first, no backend", body: "AI features run through your editor's language model support or a local CLI. Git Navigator does not require or run its own AI backend, so your diffs are not routed through a service we operate." },
      { title: "Entirely optional", body: 'On the desktop, AI is behind a build feature flag so the core product ships without "AI bloat"; in VS Code it uses the editor\'s existing language-model support. Everything Git Navigator does works with AI turned off.' },
    ],
    steps: {
      title: "Using AI in the commit flow",
      items: [
        { title: "Stage your changes", body: "Stage the files (or specific hunks) you want in the next commit, just as you would for any commit in Git Navigator." },
        { title: "Generate a message", body: "Ask Git Navigator to draft a commit message from the staged diff, then review and edit it before committing." },
        { title: "Plan a split", body: "For a large change, ask AI to propose a split into focused commits, then select the hunks for each piece in the split-commit overlay." },
      ],
    },
    faqs: [
      { q: "Does Git Navigator send my code to its own servers for AI features?", a: "No. AI features are local-first: they use your editor's language model support in VS Code, or a local CLI such as Claude Code or Codex on the desktop. Git Navigator does not run its own AI backend." },
      { q: "What can the AI actually do?", a: "Two things in the commit workflow: generate a commit message from your staged diff, and plan how to split a large change into smaller, focused commits. Both produce suggestions you review and edit — nothing is committed automatically." },
      { q: "Is AI required to use Git Navigator?", a: "No. AI assistance is entirely optional. On the desktop it sits behind a build feature flag so the app can ship without it, and every core feature works with AI turned off." },
      { q: "How does AI split planning relate to manual split commits?", a: "AI proposes a division; you carry it out with the same hunk-level split-commit flow described on the Commit Management page. The AI plan is guidance for which hunks belong together, not a separate mechanism." },
    ],
    prev: { href: "appearance.html", label: "Appearance" },
    next: { href: "entire.html", label: "Entire (Agent Sessions)" },
  },

  {
    slug: "entire",
    title: "Entire Integration (Agent Sessions)",
    breadcrumb: "Customization & AI",
    description:
      "Browse the agent sessions behind your commits. Git Navigator surfaces Entire checkpoints as an agent-session viewer, a graph overlay, expandable tool calls, full-text transcript search, and branch-filtered sessions.",
    keywords: ["entire", "agent sessions", "ai coding history", "checkpoint viewer", "claude code cursor sessions"],
    ogImage: "static/entire.png",
    heroMedia: {
      type: "image",
      src: "static/entire.png",
      alt: "Git Navigator's Entire activity: a list of agent sessions, a session's branch attribution, and its conversation timeline",
      caption:
        "The Entire activity on a real Entire-enabled repository: agent sessions on the left, the selected session's branches and details in the middle, and its full conversation timeline below.",
    },
    hero: {
      heading: "See the agent sessions behind your commits",
      lead:
        '<a href="https://entire.io" target="_blank" rel="noreferrer">Entire</a> captures agent sessions into checkpoints — git objects on <code>entire/checkpoints/v1</code>. Git Navigator adds an <strong>Entire</strong> activity that turns those checkpoints into a browsable history: the conversation timeline, the tool calls, and the commits, all cross-linked to the graph you already work in.',
    },
    highlightsTitle: "What the Entire activity shows",
    highlights: [
      { title: "Agent-session viewer", body: "Open a session and read its conversation timeline. Tool-call rows expand inline so you can see exactly what the agent ran — commands, edits, and results — alongside the messages." },
      { title: "Graph checkpoint overlay", body: "Checkpoints show up against the commit graph, so you can jump from a commit to the session that produced it and back again through the cross-links." },
      { title: "Full-text transcript search", body: "Search across session transcripts to find the moment a decision was made or a command was run, then open that session at the match." },
      { title: "Filter sessions by branch", body: "Sessions are resolved by the branches that contain their checkpoint commits — including merge targets and squash merges — with branch counts, merge-path indicators, and linked branch chips, so you can scope the list to the work you care about." },
    ],
    steps: {
      title: "Using the Entire activity",
      items: [
        { title: "Install the Entire CLI", body: "The Entire activity appears in the rail once the Entire CLI is available and the repository has checkpoints on <code>entire/checkpoints/v1</code>. Git Navigator probes for the CLI and only shows the activity when it is ready." },
        { title: "Open a session", body: "Pick a session to read its conversation timeline. Expand any tool-call row to see the underlying command and its output inline." },
        { title: "Cross-link to the graph", body: "Follow the checkpoint overlay to move between a session and the commits it produced, keeping the agent history and your git history in one place." },
        { title: "Filter and search", body: "Narrow the session list to specific branches using the branch chips, or run a full-text search across transcripts to find a specific moment." },
      ],
    },
    faqs: [
      { q: "What is the Entire integration in Git Navigator?", a: "It is an activity that surfaces Entire agent-session checkpoints — git objects stored on entire/checkpoints/v1 — as a browsable history: a session viewer with an expandable conversation timeline, a checkpoint overlay on the commit graph, cross-links between them, and full-text transcript search." },
      { q: "Why don't I see the Entire activity?", a: "The activity only appears once the Entire CLI is installed and ready and the repository has checkpoints. Git Navigator probes for the CLI at startup and keeps the activity hidden until it reports ready, so a repo without Entire checkpoints simply won't show it." },
      { q: "Can I filter agent sessions by branch?", a: "Yes. As of v0.4.0, sessions are resolved by the branches that contain their checkpoint commits — including merge targets and squash merges — and shown with branch counts, merge-path indicators, and linked branch chips so you can scope the list." },
      { q: "Which agents does this work with?", a: 'Entire captures sessions from agents such as Claude Code and Cursor; Git Navigator reads whatever checkpoints Entire has recorded for the repository. See the <a href="https://entire.io" target="_blank" rel="noreferrer">Entire</a> project for how sessions are captured.' },
    ],
    prev: { href: "ai-assistance.html", label: "AI Assistance" },
  },
];
