#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const repoRoot = path.resolve(__dirname, "..");
const changelogPath = path.join(repoRoot, "CHANGELOG.md");
const indexPath = path.join(repoRoot, "index.html");

const changelog = fs.readFileSync(changelogPath, "utf8");
const indexHtml = fs.readFileSync(indexPath, "utf8");

const versionRegex = /^##\s+\[(.+?)\]\s*-\s*(.+)$/;
const entries = [];
let current = null;

for (const line of changelog.split(/\r?\n/)) {
  const versionMatch = line.match(versionRegex);
  if (versionMatch) {
    if (current) {
      entries.push(current);
    }
    current = {
      version: versionMatch[1].trim(),
      date: versionMatch[2].trim(),
      items: [],
    };
    continue;
  }

  if (!current) {
    continue;
  }

  if (line.startsWith("- ")) {
    const item = line.slice(2).trim();
    if (item) {
      current.items.push(item);
    }
  }
}

if (current) {
  entries.push(current);
}

const limit = Number(process.env.CHANGELOG_LIMIT || 6);
const selected = entries.slice(0, limit).map(entry => ({
  ...entry,
  items: entry.items.slice(0, 6),
}));

if (selected.length === 0) {
  throw new Error("No changelog entries found.");
}

const escapeHtml = value => value
  .replace(/&/g, "&amp;")
  .replace(/</g, "&lt;")
  .replace(/>/g, "&gt;")
  .replace(/\"/g, "&quot;")
  .replace(/'/g, "&#39;");

const cards = selected.map(entry => {
  const items = entry.items.length
    ? entry.items.map(item => `              <li>${escapeHtml(item)}</li>`).join("\n")
    : "              <li>Details coming soon.</li>";

  return [
    "          <article class=\"carousel-card\">",
    `            <h3>${escapeHtml(entry.version)} · ${escapeHtml(entry.date)}</h3>`,
    "            <ul>",
    items,
    "            </ul>",
    "          </article>",
  ].join("\n");
}).join("\n");

const startMarker = "<!-- CHANGELOG_CARDS_START -->";
const endMarker = "<!-- CHANGELOG_CARDS_END -->";
const replaceRegex = new RegExp(`${startMarker}[\\s\\S]*?${endMarker}`);

if (!replaceRegex.test(indexHtml)) {
  throw new Error("Changelog markers not found in index.html.");
}

const replacement = [
  startMarker,
  "          <!-- Auto-generated by scripts/update-site.js -->",
  cards,
  endMarker,
].join("\n");

const nextHtml = indexHtml.replace(replaceRegex, replacement);
fs.writeFileSync(indexPath, nextHtml);

console.log(`Updated changelog cards with ${selected.length} entries.`);
