#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const repoRoot = path.resolve(__dirname, "..");
const changelogPath = path.join(repoRoot, "CHANGELOG.md");
const indexPath = path.join(repoRoot, "index.html");
const downloadPath = path.join(repoRoot, "download.html");

const changelog = fs.readFileSync(changelogPath, "utf8");
const indexHtml = fs.readFileSync(indexPath, "utf8");

const versionRegex = /^##\s+\[(.+?)\]\s*-\s*(.+)$/;
const entries = [];
let current = null;

for (const line of changelog.split(/\r?\n/)) {
  const versionMatch = line.match(versionRegex);
  if (versionMatch) {
    if (current) {
      entries.push(current);
    }
    current = {
      version: versionMatch[1].trim(),
      date: versionMatch[2].trim(),
      items: [],
    };
    continue;
  }

  if (!current) {
    continue;
  }

  if (line.startsWith("- ")) {
    const item = line.slice(2).trim();
    if (item) {
      current.items.push(item);
    }
  }
}

if (current) {
  entries.push(current);
}

const limit = Number(process.env.CHANGELOG_LIMIT || 6);
const selected = entries.slice(0, limit);

if (selected.length === 0) {
  throw new Error("No changelog entries found.");
}

const escapeHtml = value => value
  .replace(/&/g, "&amp;")
  .replace(/</g, "&lt;")
  .replace(/>/g, "&gt;")
  .replace(/\"/g, "&quot;")
  .replace(/'/g, "&#39;");

const cards = selected.map(entry => {
  const items = entry.items.length
    ? entry.items.map(item => `              <li>${escapeHtml(item)}</li>`).join("\n")
    : "              <li>Details coming soon.</li>";

  return [
    "          <article class=\"carousel-card\">",
    `            <h3>${escapeHtml(entry.version)} · ${escapeHtml(entry.date)}</h3>`,
    "            <ul>",
    items,
    "            </ul>",
    "          </article>",
  ].join("\n");
}).join("\n");

const startMarker = "<!-- CHANGELOG_CARDS_START -->";
const endMarker = "<!-- CHANGELOG_CARDS_END -->";
const replaceRegex = new RegExp(`${startMarker}[\\s\\S]*?${endMarker}`);

if (!replaceRegex.test(indexHtml)) {
  throw new Error("Changelog markers not found in index.html.");
}

const replacement = [
  startMarker,
  "          <!-- Auto-generated by scripts/update-site.js -->",
  cards,
  endMarker,
].join("\n");

let nextHtml = indexHtml.replace(replaceRegex, replacement);

// Keep the footer version badge in sync with the latest release so it never
// goes stale. Guard on a semver shape so a non-version heading can't write
// garbage into the footer.
const footerVersion = selected[0].version;
const footerDate = selected[0].date;
if (/^\d+\.\d+\.\d+$/.test(footerVersion)) {
  nextHtml = nextHtml.replace(
    /<span>v\d+\.\d+\.\d+ · [^<]*<\/span>/,
    `<span>v${footerVersion} · ${escapeHtml(footerDate)}</span>`,
  );
}

fs.writeFileSync(indexPath, nextHtml);

console.log(`Updated changelog cards with ${selected.length} entries.`);

// Keep the download page pinned to the latest released version so the direct
// GitHub asset URLs (which embed the version) never go stale. Guard on a
// semver shape so a non-version heading can't rewrite the URLs to garbage.
const latestVersion = selected[0].version;
const semverPattern = /^\d+\.\d+\.\d+$/;

if (semverPattern.test(latestVersion) && fs.existsSync(downloadPath)) {
  const downloadHtml = fs.readFileSync(downloadPath, "utf8");
  const nextDownloadHtml = downloadHtml
    .replace(/(data-version-label>)[\d.]+(<)/g, `$1${latestVersion}$2`)
    .replace(/Git\.Navigator_\d+\.\d+\.\d+_/g, `Git.Navigator_${latestVersion}_`)
    .replace(
      /<span>v\d+\.\d+\.\d+ · [^<]*<\/span>/,
      `<span>v${latestVersion} · ${escapeHtml(selected[0].date)}</span>`,
    );

  if (nextDownloadHtml !== downloadHtml) {
    fs.writeFileSync(downloadPath, nextDownloadHtml);
    console.log(`Updated download.html to version ${latestVersion}.`);
  } else {
    console.log(`download.html already at version ${latestVersion}.`);
  }
}
